[package]
name = "ryusi/tycoon"
version = "0.1.0"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

[dependencies]
cmdr = "evaera/cmdr@1.12.0"

[server-dependencies]
profilestore = "lm-loleris/profilestore@1.0.3"